"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: example
    version: 1.0.2

    Do not edit the class manually.
"""  # noqa: E501

from clients.http.example.apis.account_api import AccountApi
from clients.http.example.apis.login_api import LoginApi

__all__ = [
    "AccountApi",
    "LoginApi",
]
