# coding: utf-8
"""
Generated by restcodegen (https://github.com/ValeriyMenshikov/restcodegen).

    source: example
    version: 1.2.0

    Do not edit the class manually.
"""  # noqa: E501

from httpx import Response
from typing import Any

from httpx import Client


from clients.http.example.models.api_models import (
    LoginCredentials,
    UserEnvelope,
)


class LoginApi:
    def __init__(self, api_client: Client) -> None:
        self.api_client = api_client

    def post_v1_account_login(
        self,
        login_credentials: LoginCredentials,  # noqa: E501
        x_dm_bb_render_mode: str | None = None,
        **kwargs: Any,
    ) -> UserEnvelope:
        """
                Authenticate via credentials.

                Args:
                    login_credentials(LoginCredentials): ...
                    x_dm_bb_render_mode(str | None, optional): Requests with user defined texts that allows usage
        of BB-codes may be rendered differently by passing
        the X-Dm-Bb-Render-Mode header of one of following
        values Html, Bb, Text, SafeHtml
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    UserEnvelope: ...
        """  # noqa: D205,E501

        response = self.post_v1_account_login_with_http_info(
            login_credentials=login_credentials,  # noqa: E501
            x_dm_bb_render_mode=x_dm_bb_render_mode,
            **kwargs,
        )
        return UserEnvelope.model_validate_json(response.text)

    def post_v1_account_login_with_http_info(
        self,
        login_credentials: LoginCredentials,  # noqa: E501
        x_dm_bb_render_mode: str | None = None,
        **kwargs: Any,
    ) -> Response:
        """
                Authenticate via credentials.

                Args:
                    login_credentials(LoginCredentials): ...
                    x_dm_bb_render_mode(str, optional): Requests with user defined texts that allows usage
        of BB-codes may be rendered differently by passing
        the X-Dm-Bb-Render-Mode header of one of following
        values Html, Bb, Text, SafeHtml
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        # process the header parameters
        headers_map = {
            "X-Dm-Bb-Render-Mode": str(x_dm_bb_render_mode),
        }
        headers = {k: str(v) for k, v in headers_map.items() if v}
        headers.update(kwargs.pop("headers", {}))

        content = login_credentials.model_dump_json(exclude_none=True, by_alias=True)  # noqa: E501
        headers.update({"Content-Type": "application/json"})
        response = self.api_client.post(
            url="/v1/account/login",
            content=content,
            headers=headers,
            **kwargs,
        )
        return response

    def delete_v1_account_login(
        self,
        x_dm_auth_token: str,
        x_dm_bb_render_mode: str | None = None,
        **kwargs: Any,
    ) -> Response:
        """
                Logout as current user.

                Args:
                    x_dm_auth_token(str, required): Authenticated requests require X-Dm-Auth-Token
        header. You can get the data from POST /account/
        method, sending login and password in &#34;token&#34;
        response field
                    x_dm_bb_render_mode(str | None, optional): Requests with user defined texts that allows usage
        of BB-codes may be rendered differently by passing
        the X-Dm-Bb-Render-Mode header of one of following
        values Html, Bb, Text, SafeHtml
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    None: ...
        """  # noqa: D205,E501

        response = self.delete_v1_account_login_with_http_info(
            x_dm_auth_token=x_dm_auth_token,
            x_dm_bb_render_mode=x_dm_bb_render_mode,
            **kwargs,
        )
        return response

    def delete_v1_account_login_with_http_info(
        self,
        x_dm_auth_token: str,
        x_dm_bb_render_mode: str | None = None,
        **kwargs: Any,
    ) -> Response:
        """
                Logout as current user.

                Args:
                    x_dm_auth_token(str, required): Authenticated requests require X-Dm-Auth-Token
        header. You can get the data from POST /account/
        method, sending login and password in &#34;token&#34;
        response field
                    x_dm_bb_render_mode(str, optional): Requests with user defined texts that allows usage
        of BB-codes may be rendered differently by passing
        the X-Dm-Bb-Render-Mode header of one of following
        values Html, Bb, Text, SafeHtml
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        # process the header parameters
        headers_map = {
            "X-Dm-Auth-Token": str(x_dm_auth_token),
            "X-Dm-Bb-Render-Mode": str(x_dm_bb_render_mode),
        }
        headers = {k: str(v) for k, v in headers_map.items() if v}
        headers.update(kwargs.pop("headers", {}))

        response = self.api_client.delete(
            url="/v1/account/login",
            headers=headers,
            **kwargs,
        )
        return response

    def delete_v1_account_login_all(
        self,
        x_dm_auth_token: str,
        x_dm_bb_render_mode: str | None = None,
        **kwargs: Any,
    ) -> Response:
        """
                Logout from every device.

                Args:
                    x_dm_auth_token(str, required): Authenticated requests require X-Dm-Auth-Token
        header. You can get the data from POST /account/
        method, sending login and password in &#34;token&#34;
        response field
                    x_dm_bb_render_mode(str | None, optional): Requests with user defined texts that allows usage
        of BB-codes may be rendered differently by passing
        the X-Dm-Bb-Render-Mode header of one of following
        values Html, Bb, Text, SafeHtml
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    None: ...
        """  # noqa: D205,E501

        response = self.delete_v1_account_login_all_with_http_info(
            x_dm_auth_token=x_dm_auth_token,
            x_dm_bb_render_mode=x_dm_bb_render_mode,
            **kwargs,
        )
        return response

    def delete_v1_account_login_all_with_http_info(
        self,
        x_dm_auth_token: str,
        x_dm_bb_render_mode: str | None = None,
        **kwargs: Any,
    ) -> Response:
        """
                Logout from every device.

                Args:
                    x_dm_auth_token(str, required): Authenticated requests require X-Dm-Auth-Token
        header. You can get the data from POST /account/
        method, sending login and password in &#34;token&#34;
        response field
                    x_dm_bb_render_mode(str, optional): Requests with user defined texts that allows usage
        of BB-codes may be rendered differently by passing
        the X-Dm-Bb-Render-Mode header of one of following
        values Html, Bb, Text, SafeHtml
                    **kwargs: Arguments supported by the httpx library (data, files, headers, etc.)

                Returns:
                    Response: ...
        """  # noqa: D205,E501
        # process the header parameters
        headers_map = {
            "X-Dm-Auth-Token": str(x_dm_auth_token),
            "X-Dm-Bb-Render-Mode": str(x_dm_bb_render_mode),
        }
        headers = {k: str(v) for k, v in headers_map.items() if v}
        headers.update(kwargs.pop("headers", {}))

        response = self.api_client.delete(
            url="/v1/account/login/all",
            headers=headers,
            **kwargs,
        )
        return response
